services:
  - type: worker
    name: queue
    region: frankfurt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery --app tasks worker --loglevel info --concurrency 4"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
  - type: web
    name: app
    region: frankfurt
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app"
    autoDeploy: false
    envVars:
      - key: DEBUG 
        value: False 
      - key: CLOUD_DB
        value: True
      - key: ALLOWED_HOSTS
        value: '*'
      - key: JUMIA_SMARTPHONE_URL
        value: https://www.jumia.co.ke/smartphones/
      - key: JUMIA_LIQOUR_URL
        value: https://www.jumia.co.ke/spirits-liquors/
      - key: POSTGRESDB_URL
        fromDatabase:
          name: scraper-postgres
          property: connectionString
      - key: REDIS_URL
        fromService:
          name: celery-redis
          type: redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
  - type: web
    name: flower
    region: frankfurt
    plan: free
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "celery flower --app tasks --loglevel info"
    autoDeploy: false
    envVars:
      - key: CELERY_BROKER_URL
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
      - key: CELERY_RESULT_BACKEND
        fromService:
          type: redis
          name: celery-redis
          property: connectionString
  - type: redis
    name: celery-redis
    region: frankfurt
    plan: free
    maxmemoryPolicy: noeviction 
    ipAllowList: ['0.0.0.0',] 

databases:
  - name: scraper-postgres
    user: scraperApp