# Generated by Django 4.2.1 on 2023-06-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='official_store',
            field=models.CharField(default='Empty', max_length=255),
            preserve_default=False,
        ),
    ]
